version: "2.24.5"
services:
 web:
  build: .
  working_dir: /data
  command: python _rotas.py
  restart: always
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5050:5050"

 db:
  image: mysql:8.0.34
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
  ports:
    - "3306:3306"