FROM python:3.11-alpine

RUN python -m pip install --upgrade pip
RUN pip install Flask
RUN pip install Flask-Mail
RUN pip install requests
RUN pip install mysql-connector-python
RUN apk add --no-cache mariadb-connector-c-dev

COPY main.py /main.py
ENV FLASK_APP=main.py
CMD [ "python", "main.py" ]