# Usando a imagem oficial do MySQL 8.0 como base
FROM mysql:8.0.34

LABEL maintainer "Sabrina Malafaia"

# Variáveis de ambiente para configuração do MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=V2
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=50748523

# Copie um arquivo SQL de inicialização para criar o banco de dados
COPY ./query.sql /docker-entrypoint-initdb.d/