version: "2.24.5"
services:
 bd:
  build:
    dockerfile: dockerfile.mysql
  ports:
    - "3307:3306"
  restart: always

 web:
  build:
    dockerfile: dockerfile.python
  working_dir: /data
  command: python main.py
  depends_on:
    - bd
  volumes:
    - .:/data
  ports:
    - "5050:5050"
  restart: always