CREATE DATABASE IF NOT EXISTS V2;

USE V2;

CREATE TABLE IF NOT EXISTS parceiros(
id_parceiro INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
parceiro VARCHAR(100) NOT NULL,
cep CHAR(8) NOT NULL,    
endereco VARCHAR(255) NOT NULL,
complemento VARCHAR(100),
bairro VARCHAR(100) NOT NULL,
cidade VARCHAR(100) NOT NULL,
estado CHAR(2) NOT NULL,
contato VARCHAR(255) NOT NULL,
responsavel VARCHAR(255) NOT NULL,
desconto DECIMAL(10, 2),
detalhes TEXT,
data DATE,
status ENUM('0', '1') NOT NULL
);

CREATE TABLE IF NOT EXISTS grupos(
id_grupo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
grupo VARCHAR(100) NOT NULL,    
cep CHAR(8) NOT NULL,    
endereco VARCHAR(255) NOT NULL,
complemento VARCHAR(100),
bairro VARCHAR(100) NOT NULL,
cidade VARCHAR(100) NOT NULL,
estado CHAR(2) NOT NULL,
contato VARCHAR(255) NOT NULL,
responsavel VARCHAR(255) NOT NULL,
detalhes TEXT,
data DATE,
status ENUM('0', '1') NOT NULL
);

CREATE TABLE IF NOT EXISTS tipoUsuario (
id_tipo INT PRIMARY KEY AUTO_INCREMENT,
tipo ENUM('ADM', 'USER') UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
id_usuario INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) UNIQUE NOT NULL,
senha VARCHAR(100) NOT NULL,
nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventos (
id_evento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(100) NOT NULL,
descricao TEXT NOT NULL,
data_inicio DATETIME NOT NULL,
data_fim DATETIME NOT NULL,
localizacao VARCHAR(100) NOT NULL
);